ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS return_requested BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS return_reason VARCHAR(255),
    ADD COLUMN IF NOT EXISTS return_note TEXT;

ALTER TABLE addresses
    ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(255),
    ADD COLUMN IF NOT EXISTS state VARCHAR(128);
